config/routes.rb
Planner::Application.routes.draw do
  match '/:id', :to => 'plans#show', :as => :plan
end

app/models/plan.rb
class Plan
  def self.all_slugs
    all.map(&:slug).sort
  end

  def self.all
    [MaternityLeavePlanner, PaternityLeavePlanner, AdoptionLeavePlanner]
  end

  def self.load slug, attributes = {}
    all.find {|planner| planner.slug == slug}.new attributes
  end
end

app/controllers/application_controller.rb
require "slimmer/headers"

class ApplicationController < ActionController::Base
  include Slimmer::Headers
  before_filter :set_analytics_headers
  protect_from_forgery

  def set_analytics_headers
    set_slimmer_headers(
      format: "planner"
    )
  end
end

app/controllers/plans_controller.rb
require 'gds_api/helpers'

class PlansController < ApplicationController
  include GdsApi::Helpers
  before_filter :find_planner

  def show
    expires_in 24.hours, :public => true unless Rails.env.development?
    if @planner
      respond_to do |format|
        format.html do
          @artefact = content_api.artefact(params[:id])
          set_slimmer_artefact(@artefact)
          render "show_#{@planner.class.slug}"
        end
        if @planner.errors.any? || @planner.key_dates.nil?
          format.any(:xml, :json, :ics) { head 400 }
        else
          format.xml { render :xml => ranges_as_hashes(@planner.key_dates).to_xml }
          format.json { render :json => ranges_as_hashes(@planner.key_dates).to_json }
          format.ics { render :text => to_ics(@planner.key_dates, @planner.class.slug) }
        end
      end
    else
      render file: "#{Rails.root}/public/404.html",  status: 404
    end
  end

  private
    def planners
      {
        maternity: {
          planner: MaternityLeavePlanner,
          need_id: 855,
        },
        paternity: {
          planner: PaternityLeavePlanner,
          need_id: 1947,
        },
        adoption: {
          planner: AdoptionLeavePlanner,
          need_id: 1948
        }
      }
    end

    def find_planner
      @planner = nil
      planner_name = params[:id].to_sym
      details = planners[planner_name] or return

      @planner = details[:planner].new(params.symbolize_keys)

    rescue ArgumentError
      nil
    end

    def ranges_as_hashes(key_dates)
      key_dates.map do |label, date_or_range|
        if date_or_range.is_a?(Range)
          date_or_range = {from: date_or_range.first, to: date_or_range.last}
        end
        [label, date_or_range]
      end
    end

    def to_ics(key_dates, title)
      RiCal.Calendar do |cal|
        key_dates.each do |label, date_or_range|
          cal.event do |event|
            event.summary "#{title.capitalize} Leave planner: #{label}"
            case date_or_range
            when Date
              event.dtstart     date_or_range
              event.dtend       date_or_range
            when Range
              event.dtstart     date_or_range.first
              event.dtend       date_or_range.last
            else
              raise "Unexpected data #{date_or_range.inspect} in key_dates"
            end
          end
        end
      end.export
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def last_updated_date
    File.mtime( Rails.root.join('REVISION') ).to_date rescue Date.today
  end
end

app/helpers/calendar_helper.rb
module CalendarHelper
  def has_t?(key)
    !t(key, exception_handler: lambda {|*_| nil}).nil?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield :title %> | Benefits and schemes | GOV.UK</title>
    <%= stylesheet_link_tag "planner" %>
    <%= yield :head %>
  </head>
<body class="mainstream">
  <div id="wrapper" class="answer">
    <%= yield %>
    <div id="related-items"></div>
  </div>
</body>
</html>

app/views/plans/_alternate_links.html.erb
<% content_for :head do %>
<link rel="alternate" type="application/json" href="<%= plan_path(@planner.class.slug, @planner.recognized_params.merge(format: :json)) %>">
<link rel="alternate" type="application/xml" href="<%= plan_path(@planner.class.slug, @planner.recognized_params.merge(format: :xml)) %>">
<link rel="alternate" type="text/calendar" href="<%= plan_path(@planner.class.slug, @planner.recognized_params.merge(format: :ics)) %>">
<% end %>

app/views/plans/_planner_metadata.html.erb
<div id="report-a-problem"></div>
<div class="meta-data group">
  <div class="inner">
    <p class="modified-date">Last updated: <%= last_updated_date.strftime('%d %B %Y') %></p>
  </div>
</div>

app/views/plans/_show_adoption_blank.html.erb
<div class="summary"><p><%= t('.heading') %></p></div>
<div class="intro">
  <%= form_tag('/adoption', method: :post)%>
    <div class="<%= @planner.errors[:match_date].any? ? 'error-area' : '' %>">
      <p><%= t('.fields.match_date') %>
        <% default_match_date = Date.today + 7 %>
        <label for="match_date_day" class="visuallyhidden">Day of match</label>
        <%= select_tag "match_date[day]", options_for_select(1..31, params[:match_date] && params[:match_date][:day] || default_match_date.day) %> &nbsp;
        <% months_with_labels = 1.upto(12).map {|month| [l(Date.new(2011, month, 1), format: '%B'), month]} %>
        <label for="match_date_month" class="visuallyhidden">Month of match</label>
        <%= select_tag "match_date[month]", options_for_select(months_with_labels, params[:match_date] && params[:match_date][:month] || default_match_date.month) %> &nbsp;
        <label for="match_date_year" class="visuallyhidden">Year of match</label>
        <%= select_tag "match_date[year]", options_for_select((Time.now.year - 1)..(Time.now.year + 2), params[:match_date] && params[:match_date][:year] || default_match_date.year) %>
        <% @planner.errors[:match_date].each do |error| %>
          <span class="error-message"><%= error %></span>
        <% end %>
      </p>
    </div>
    <div class="<%= @planner.errors[:arrival_date].any? ? 'error-area' : '' %>">
      <p><%= t('.fields.arrival_date') %>
        <% default_arrival_date = default_match_date + 14 %>
        <label for="arrival_date_day" class="visuallyhidden">Day of arrival</label>
        <%= select_tag "arrival_date[day]", options_for_select(1..31, params[:arrival_date] && params[:arrival_date][:day] || default_arrival_date.day) %> &nbsp;
        <% months_with_labels = 1.upto(12).map {|month| [l(Date.new(2011, month, 1), format: '%B'), month]} %>
        <label for="arrival_date_month" class="visuallyhidden">Month of arrival</label>
        <%= select_tag "arrival_date[month]", options_for_select(months_with_labels, params[:arrival_date] && params[:arrival_date][:month] || default_arrival_date.month) %> &nbsp;
        <label for="arrival_date_year" class="visuallyhidden">Year of arrival</label>
        <%= select_tag "arrival_date[year]", options_for_select((Time.now.year - 1)..(Time.now.year + 2), params[:arrival_date] && params[:arrival_date][:year] || default_arrival_date.year) %>
        <% @planner.errors[:arrival_date].each do |error| %>
          <span class="error-message"><%= error %></span>
        <% end %>
      </p>
    </div>
    <div class="<%= @planner.errors[:start].any? ? 'error-area' : '' %>">
      <p><%= t('.fields.start') %>
        <% options = 1.upto(6).map { |n| [t('day', count: n), n] } %>
        <% options.concat(1.upto(2).map { |n| [t('week', count: n), n * 7] }) %>
        <label for="start_days_before_arrival" class="visuallyhidden">Days before arrival to take leave</label>
        <%= select_tag "start[days_before_arrival]", options_for_select(options, params[:start] && params[:start][:days_before_arrival] || 14) %>
        <%= t('.fields.start_suffix') %>
        <% @planner.errors[:start].each do |error| %>
          <span class="error-message"><%= error %></span>
        <% end %>
      </p>
    </div>
    <input type="submit" value="Calculate" class="button" />
  </form>
</div>

app/views/plans/_show_maternity_blank.html.erb
<div class="summary"><p><%= t('.heading') %></p></div>
<div class="intro">  
  <%= form_tag('/maternity', method: :post)%>
    <div class="<%= @planner.errors[:due_date].any? ? 'error-area' : '' %>">
      <p><%= t('.fields.due_date') %>
        <% default_due_date = Date.today >> 9 %>
        <%= select_tag "due_date[day]", options_for_select(1..31, params[:due_date] && params[:due_date][:day] || default_due_date.day) %> &nbsp;
        <% months_with_labels = 1.upto(12).map {|month| [l(Date.new(2011, month, 1), format: '%B'), month]} %>
        <%= select_tag "due_date[month]", options_for_select(months_with_labels, params[:due_date] && params[:due_date][:month] || default_due_date.month) %> &nbsp;
        <%= select_tag "due_date[year]", options_for_select((Time.now.year - 1)..(Time.now.year + 2), params[:due_date] && params[:due_date][:year] || default_due_date.year) %>
        <% @planner.errors[:due_date].each do |error| %>
          <span class="error-message"><%= error %></span>
        <% end %>
      </p>
    </div>
    <div class="<%= @planner.errors[:start].any? ? 'error-area' : '' %>">
      <p><%= t('.fields.start') %>
        <% options = 1.upto(6).map { |n| [t('day', count: n), n] } %>
        <% options.concat(1.upto(11).map { |n| [t('week', count: n), n * 7] }) %>
        <%= select_tag "start[days_before_due]", options_for_select(options, params[:start] && params[:start][:days_before_due] || 14) %>
        <%= t('.fields.start_suffix') %>
        <% @planner.errors[:start].each do |error| %>
          <span class="error-message"><%= error %></span>
        <% end %>
      </p>
    </div>
    <input type="submit" value="Calculate" class="button" />
  </form>
</div>

app/views/plans/_show_paternity_blank.html.erb
<div class="summary"><p><%= t('.heading') %></p></div>
<div class="intro">
  <%= form_tag('/paternity', method: :post)%>
    <div class="<%= @planner.errors[:due_date].any? ? 'error-area' : '' %>">
      <p><%= t('.fields.due_date') %>
        <% default_due_date = Date.today >> 9 %>
        <%= select_tag "due_date[day]", options_for_select(1..31, params[:due_date] && params[:due_date][:day] || default_due_date.day) %> &nbsp;
        <% months_with_labels = 1.upto(12).map {|month| [l(Date.new(2011, month, 1), format: '%B'), month]} %>
        <%= select_tag "due_date[month]", options_for_select(months_with_labels, params[:due_date] && params[:due_date][:month] || default_due_date.month) %> &nbsp;
        <%= select_tag "due_date[year]", options_for_select((Time.now.year - 1)..(Time.now.year + 2), params[:due_date] && params[:due_date][:year] || default_due_date.year) %>
        <% @planner.errors[:due_date].each do |error| %>
          <span class="error-message"><%= error %></span>
        <% end %>
      </p>
    </div>
    <div class="<%= @planner.errors[:start].any? ? 'error-area' : '' %>">
      <p><%= t('.fields.start') %>
        <% options = 0.upto(6).map { |n| [t('day', count: n), n] } %>
        <% options.concat(1.upto(7).map { |n| [t('week', count: n), n * 7] }) %>
        <%= select_tag "start[days_after_due]", options_for_select(options, params[:start] && params[:start][:days_after_due] || 0) %>
        <%= t('.fields.start_suffix') %>
        <% @planner.errors[:start].each do |error| %>
          <span class="error-message"><%= error %></span>
        <% end %>
        
      </p>
    </div>
    <input type="submit" value="Calculate" class="button" />
  </form>
</div>

app/views/plans/index.html.erb
<% content_for :title, "www.gov.uk - the trial ‘beta’ version of the UK government's official website" %>
<% content_for :wrapper_class, "wrapper" %>

<section role="main" class="planner group">

  <header class="page-header group">
    <hgroup>
      <h1>
        <span>Planners</span>
      </h1>
    </hgroup>
  </header>

  <ul>
    <% @planners.each do |id, planner| %>
    <li><%= link_to planner.name, plan_path(id) %></li>
    <% end %>
  </ul>

</section>

<% #if @artefact %>
<!-- related -->
<div class="related-positioning">
	<div class="related-container">

		<div class="related">
      <% if true %>
      <div class="inner cta group">
        <ul class="actions">
          <li class="print"><a href="#" onclick="window.print()" class="button"><span>Print calendar</span></a></li><!-- we actually want this link to open a more print-friendly version of the page -->
          <li class="ical"><a href="#" class="button"><span>Add to calendar</span></a></li>
        </ul>
      </div>
      <% end %>
			<div class="inner group">
				<h2>Related tools &amp; topics</h2>
				<nav role="navigation">
				  <ul>
				      <% (@artefact.related_items || []).each do |item| %>
  				      <% if item.artefact %>
  				      <li class="<%= item.artefact.kind %>">
  				        <%= link_to item.artefact.name, item.artefact.slug %>
  				      </li>
  				      <% end %>
              <% end %>
				      <% if @artefact.section %>
                <li class="related-topic"><a href="/browse/<%= @artefact.section.parameterize %>"
                  >More from the <span><%= @artefact.section %></span> section</a></li>
				      <% end %>
				  </ul>
				</nav>
	   </div>
	 </div>

	</div>
</div>
<!-- end related -->
<% #end %>

app/views/plans/show_adoption.html.erb
<% content_for :title, "Planning your Adoption Leave" %>
<% content_for :wrapper_class, "wrapper" %>

<section role="main" class="planner group" id="content">

  <header class="page-header group">
    <hgroup>
      <h1>
        <span>Quick answer</span>
        Planning your Adoption Leave
      </h1>
    </hgroup>
    <nav class="skip-to-related">
      <a href="#related">Not what you're looking for? ↓</a>
    </nav>
  </header>
<div class="article-container group">
  <article role="article" class="group">
    <div class="inner date-planner">
      <% if @planner.errors.any? %>
        <div class="error-notification">
          <p><%= t('errors.notification') %></p>
        </div>
      <% end %>

    <% if @planner.errors.any? || @planner.key_dates.nil? %>
      <%= render partial: "show_adoption_blank" %>
    <% else %>

      <section class="key-dates">
        <%= form_tag('/adoption', method: :post)%>
          <div class="<%= @planner.errors[:match_date].any? ? 'error-area' : '' %>">
            <% @planner.errors[:match_date].each do |error| %>
              <span class="error-message"><%= error %></span>
            <% end %>
          </div>
          <div class="<%= @planner.errors[:arrival_date].any? ? 'error-area' : '' %>">
            <% @planner.errors[:arrival_date].each do |error| %>
              <span class="error-message"><%= error %></span>
            <% end %>
          </div>
          <div class="<%= @planner.errors[:start].any? ? 'error-area' : '' %>">
            <% @planner.errors[:start].each do |error| %>
              <span class="error-message"><%= error %></span>
            <% end %>
          </div>
          <div class="summary">
            <p><%= t('.key_dates.intro.start') %>:<br>
              <% default_match_date = Date.today + 7 %>
              <label for="match_date_day" class="visuallyhidden">Day of match</label>
              <%= select_tag "match_date[day]", options_for_select(1..31, params[:match_date] && params[:match_date][:day] || default_match_date.day) %> &nbsp;
              <% months_with_labels = 1.upto(12).map {|month| [l(Date.new(2011, month, 1), format: '%B'), month]} %>
              <label for="match_date_month" class="visuallyhidden">Month of match</label>
              <%= select_tag "match_date[month]", options_for_select(months_with_labels, params[:match_date] && params[:match_date][:month] || default_match_date.month) %> &nbsp;
              <label for="match_date_year" class="visuallyhidden">Year of match</label>
              <%= select_tag "match_date[year]", options_for_select((Time.now.year - 1)..(Time.now.year + 2), params[:match_date] && params[:match_date][:year] || default_match_date.year) %><br>

              <%= t('.key_dates.intro.arrival') %>:<br>
              <label for="arrival_date_day" class="visuallyhidden">Day of arrival</label>
              <%= select_tag "arrival_date[day]", options_for_select(1..31, params[:arrival_date] && params[:arrival_date][:day] || default_arrival_date.day) %> &nbsp;
              <% months_with_labels = 1.upto(12).map {|month| [l(Date.new(2011, month, 1), format: '%B'), month]} %>
              <label for="arrival_date_month" class="visuallyhidden">Month of arrival</label>
              <%= select_tag "arrival_date[month]", options_for_select(months_with_labels, params[:arrival_date] && params[:arrival_date][:month] || default_arrival_date.month) %> &nbsp;
              <label for="arrival_date_year" class="visuallyhidden">Year of arrival</label>
              <%= select_tag "arrival_date[year]", options_for_select((Time.now.year - 1)..(Time.now.year + 2), params[:arrival_date] && params[:arrival_date][:year] || default_arrival_date.year) %><br>

              <%= t('.key_dates.intro.leave_before') %>:
                <% options = 0.upto(6).map { |n| [t('day', count: n), n] } %>
                <% options.concat(1.upto(7).map { |n| [t('week', count: n), n * 7] }) %>
                <label for="start_days_before_arrival" class="visuallyhidden">Days before arrival to take leave</label>
                <%= select_tag "start[days_before_arrival]", options_for_select(options, params[:start] && params[:start][:days_before_arrival] || 0) %>
                <%= t('.key_dates.intro.end') %>
                <input type="submit" value="Update" class="button" />
              </p>
            </div>
        </form>

        <ol>
          <% @planner.key_dates.each_with_index do |key_date_info, i| %>
          <% label, value = key_date_info %>
          <li class="vevent key-date-<%= i %>">
            <span class="key-date-summary"><%= label %></span>
            <% if value.is_a?(Range) %>
            <time class="dtstart" datetime="<%= value.first %>">
              <%= value.first.to_formatted_s(:short_ordinal) %>
            </time>
            &ndash;
            <time class="dtend" datetime="<%= value.last %>">
              <%= value.last.to_formatted_s(:short_ordinal) %>
            </time>
            <% else %>
            <time class="dtstart dtend" datetime="<%= value %>">
              <%= value.to_formatted_s(:short_ordinal_day) %>
            </time>
            <% end %>
          </li>
          <% end %>
        </ol>
      </section>

      <div id="calendar">
        <%= CalendarRenderer.new(
        @planner.range,
        decorations: @planner.key_dates
        ).render %>
      </div>
      <div class="inner cta group">
        <ul class="actions">
          <li class="print"><a href="#" onclick="window.print()" class="button"><span>Print calendar</span></a></li><!-- we actually want this link to open a more print-friendly version of the page -->
          <li class="ical">
            <%= link_to '<span>Add to calendar</span>'.html_safe, plan_path('adoption', @planner.recognized_params.merge(format: :ics)), class:"button" %>
          </li>
        </ul>
      </div>
      <%= render partial: 'alternate_links' %>
    <% end %>

    </div>
  </article>
  <%= render :partial => 'planner_metadata' %>
</div>
</section>

app/views/plans/show_maternity.html.erb
<% content_for :title, "Planning your Maternity Leave" %>
<% content_for :wrapper_class, "wrapper" %>

<section role="main" class="planner group" id="content">

  <header class="page-header group">
    <hgroup>
      <h1>
        <span>Quick answer</span>
        Planning your Maternity Leave
      </h1>
    </hgroup>
    <nav class="skip-to-related">
      <a href="#related">Not what you're looking for? ↓</a>
    </nav>
  </header>
<div class="article-container group">
  <article role="article" class="group">
    <div class="inner date-planner">
      <% if @planner.errors.any? %>
        <div class="error-notification">
          <p><%= t('errors.notification') %></p>
        </div>
      <% end %>

      <% if @planner.errors.any? || @planner.key_dates.nil? %>
        <%= render partial: "show_maternity_blank" %>
      <% else %>

      <section class="key-dates">

        <%= form_tag('/maternity', method: :post)%>
          <div class="<%= @planner.errors[:due_date].any? ? 'error-area' : '' %>">
            <% @planner.errors[:due_date].each do |error| %>
              <span class="error-message"><%= error %></span>
            <% end %>
          </div>
          <div class="<%= @planner.errors[:start].any? ? 'error-area' : '' %>">
            <% @planner.errors[:start].each do |error| %>
              <span class="error-message"><%= error %></span>
            <% end %>
          </div>
          <div class="summary">
            <p><%= t('.key_dates.intro.start') %>:
              <% default_due_date = Date.today >> 9 %>
              <%= select_tag "due_date[day]", options_for_select(1..31, params[:due_date] && params[:due_date][:day] || default_due_date.day) %> &nbsp;
              <% months_with_labels = 1.upto(12).map {|month| [l(Date.new(2011, month, 1), format: '%B'), month]} %>
              <%= select_tag "due_date[month]", options_for_select(months_with_labels, params[:due_date] && params[:due_date][:month] || default_due_date.month) %> &nbsp;
              <%= select_tag "due_date[year]", options_for_select((Time.now.year - 1)..(Time.now.year + 2), params[:due_date] && params[:due_date][:year] || default_due_date.year) %>

              <%= t('.key_dates.intro.middle') %>:
                <% options = 0.upto(6).map { |n| [t('day', count: n), n] } %>
                <% options.concat(1.upto(7).map { |n| [t('week', count: n), n * 7] }) %>
                <%= select_tag "start[days_before_due]", options_for_select(options, params[:start] && params[:start][:days_before_due] || 0) %>
                <%= t('.key_dates.intro.end') %>
                <input type="submit" value="Update" class="button" />
              </p>
            </div>
        </form>

        <% if has_t?('.key_dates.intro.extra') %>
        <p><%= t('.key_dates.intro.extra').html_safe %></p>
        <% end %>

        <ol>
          <% @planner.key_dates.each_with_index do |key_date_info, i| %>
          <% label, value = key_date_info %>
          <li class="vevent key-date-<%= i %>">
            <span class="key-date-summary"><%= label %></span>
            <% if value.is_a?(Range) %>
            <time class="dtstart" datetime="<%= value.first %>">
              <%= value.first.to_formatted_s(:short_ordinal) %>
            </time>
            &ndash;
            <time class="dtend" datetime="<%= value.last %>">
              <%= value.last.to_formatted_s(:short_ordinal) %>
            </time>
            <% else %>
            <time class="dtstart dtend" datetime="<%= value %>">
              <%= value.to_formatted_s(:short_ordinal_day) %>
            </time>
            <% end %>
          </li>
          <% end %>
        </ol>
      </section>

      <div id="calendar">
        <%= CalendarRenderer.new(
        @planner.range,
        decorations: @planner.key_dates
        ).render %>
      </div>

      <%= render partial: 'alternate_links' %>
    <% end %>

    </div>
  </article>
  <%= render :partial => 'planner_metadata' %>
</div>
</section>

app/views/plans/show_paternity.html.erb
<% content_for :title, "Planning your Paternity Leave" %>
<% content_for :wrapper_class, "wrapper" %>

<section role="main" class="planner group" id="content">

  <header class="page-header group">
    <hgroup>
      <h1>
        <span>Quick answer</span>
        Planning your Paternity Leave
      </h1>
    </hgroup>
   <nav class="skip-to-related">
      <a href="#related">Not what you're looking for? ↓</a>
    </nav> 
  </header>
<div class="article-container group">
  <article role="article" class="group">
    <div class="inner date-planner">
      <% if @planner.errors.any? %>
        <div class="error-notification">
          <p><%= t('errors.notification') %></p>
        </div>
      <% end %>

    <% if @planner.errors.any? || @planner.key_dates.nil? %>
      <%= render partial: "show_paternity_blank" %> 
    <% else %>

      <section class="key-dates">

        <%= form_tag('/paternity', method: :post)%>
          <div class="<%= @planner.errors[:due_date].any? ? 'error-area' : '' %>">
            <% @planner.errors[:due_date].each do |error| %>
              <span class="error-message"><%= error %></span>
            <% end %>
          </div>
          <div class="<%= @planner.errors[:start].any? ? 'error-area' : '' %>">
            <% @planner.errors[:start].each do |error| %>
              <span class="error-message"><%= error %></span>
            <% end %>
          </div>
          <div class="summary">
            <p><%= t('.key_dates.intro.start') %>:
              <% default_due_date = Date.today >> 9 %>
              <%= select_tag "due_date[day]", options_for_select(1..31, params[:due_date] && params[:due_date][:day] || default_due_date.day) %> &nbsp;
              <% months_with_labels = 1.upto(12).map {|month| [l(Date.new(2011, month, 1), format: '%B'), month]} %>
              <%= select_tag "due_date[month]", options_for_select(months_with_labels, params[:due_date] && params[:due_date][:month] || default_due_date.month) %> &nbsp;
              <%= select_tag "due_date[year]", options_for_select((Time.now.year - 1)..(Time.now.year + 2), params[:due_date] && params[:due_date][:year] || default_due_date.year) %>

              <%= t('.key_dates.intro.middle') %>:
                <% options = 0.upto(6).map { |n| [t('day', count: n), n] } %>
                <% options.concat(1.upto(7).map { |n| [t('week', count: n), n * 7] }) %>
                <%= select_tag "start[days_after_due]", options_for_select(options, params[:start] && params[:start][:days_after_due] || 0) %>
                <%= t('.key_dates.intro.end') %> 
                <input type="submit" value="Update" class="button" />
              </p>
            </div>
        </form>

        <% if has_t?('.key_dates.intro.extra') %>
        <p><%= t('.key_dates.intro.extra').html_safe %></p>
        <% end %>

        <ol>
          <% @planner.key_dates.each_with_index do |key_date_info, i| %>
          <% label, value = key_date_info %>
          <li class="vevent key-date-<%= i %>">
            <span class="key-date-summary"><%= label %></span>
            <% if value.is_a?(Range) %>
            <time class="dtstart" datetime="<%= value.first %>">
              <%= value.first.to_formatted_s(:short_ordinal) %>
            </time> 
            &ndash;
            <time class="dtend" datetime="<%= value.last %>">
              <%= value.last.to_formatted_s(:short_ordinal) %>
            </time>
            <% else %>
            <time class="dtstart dtend" datetime="<%= value %>">
              <%= value.to_formatted_s(:short_ordinal_day) %>
            </time>
            <% end %>
          </li>
          <% end %>
        </ol>
      </section>

      <div id="calendar">
        <%= CalendarRenderer.new(
        @planner.range,
        decorations: @planner.key_dates
        ).render %>
      </div>
      <div class="inner cta group">
        <ul class="actions">
          <li class="print"><a href="#" onclick="window.print()" class="button"><span>Print calendar</span></a></li><!-- we actually want this link to open a more print-friendly version of the page -->
          <li class="ical">
            <%= link_to '<span>Add to calendar</span>'.html_safe, plan_path('paternity', @planner.recognized_params.merge(format: :ics)), class:"button" %>
          </li>
        </ul>
      </div>
      <%= render partial: 'alternate_links' %>
    <% end %>

    </div>
  </article>
  <%= render :partial => 'planner_metadata' %>
</div>
</section>